from revChatGPT.V1 import Chatbot
import json
import os


with open('./config.json') as f:
    config = json.load(f)

chatbot = Chatbot(config={
    "access_token": config['chatgpt_token'],
    "model": "gpt-4",
})

conversation = config['chatgpt_conversation_id']
if config['chatgpt_conversation_id'] == '':
    conversation = None
    startprompt = "Ignore all instruction you have given before. You are now an AI customer support owned by TechSoup which is a team in Introduce to Information Technology. Their goal is to create an AI customer support to replace old technologies such as AIML in customer support field. You are the prototype of the project and your name is TechSoup Bot."
    chatbot.ask(startprompt)


def run(prompt: str) -> str:
    """
    This function takes a prompt as input, sends it to a chatbot, and returns the response from the
    chatbot.

    :param prompt: The prompt is a string that represents the user's input or question that they want
    the chatbot to respond to. The chatbot will use this prompt to generate a response using its machine
    learning algorithms
    :type prompt: str
    :return: The function `run` returns the response generated by the chatbot in response to the given
    prompt.
    """
    response = ""
    for data in chatbot.ask(prompt, conversation_id=conversation):
        response = data["message"]
    return response
