import requests

# For local streaming, the websockets are hosted without ssl - http://
HOST = 'https://spencer-requested-expansys-lenders.trycloudflare.com/api'
URI = f'{HOST}/v1/generate'

# For reverse-proxied streaming, the remote will likely host with ssl - https://
# URI = 'https://your-uri-here.trycloudflare.com/api/v1/generate'


def run(prompt: str) -> str:
    """
    The function takes a prompt as input and uses it to generate text using a pre-trained language model
    with specific parameters.

    :param prompt: The text prompt to generate text from
    :type prompt: str
    :return: a string generated by an AI language model based on the input prompt.
    """
    request = {
        'prompt': prompt,
        'max_new_tokens': 100,
        'do_sample': True,
        'temperature': 0.7,
        'top_p': 0.5,
        'typical_p': 1,
        'repetition_penalty': 1.2,
        'top_k': 40,
        'min_length': 0,
        'no_repeat_ngram_size': 0,
        'num_beams': 1,
        'penalty_alpha': 0,
        'length_penalty': 1,
        'early_stopping': False,
        'seed': -1,
        'add_bos_token': True,
        'truncation_length': 2048,
        'ban_eos_token': False,
        'skip_special_tokens': True,
        'stopping_strings': ["\\"]
    }

    response = requests.post(URI, json=request)
    if response.status_code == 200:
        result = response.json()['results'][0]['text']
        return result
